---
#The default size is 0.8 beacuse the pickaxe gonna stick out
size: 0.8

blocks:
  #if this is false than it would mine everything expect the cannot but wont smelt it auto
  #if this is true it would act like normal pickaxe
  normal: true
  #Blocks that cannot be broken
  #ids of block that cannot be broken
  cannot: [7, 20, 90]

level:
  #every level it will cost 10 * level
  cost: 15
  #this is the max level
  max: 15
...