---
tsunadesenja: "off"
duykhoa2008: "off"
xunek2008: "on"
khangmine8725: "off"
noobofblind: "off"
baojoker1936: "on"
huypro5406: "off"
thanhreal7026: "off"
novastark1245: "off"
kingbearpe: "off"
...
