---
datetime-format: "H:i:s"
Motd:
  update-timeout: 1
  custom: false
  message: "&e[{TIME}] &aWelcome to your server! &n&b[{TOTALPLAYERS}/{MAXPLAYERS}]"
OutdatedClient:
  custom: false
  message: "&cYour MCPE client is outdated!"
OutdatedServer:
  custom: false
  message: "&cOops! Server outdated!"
WhitelistedServer:
  custom: false
  message: "&c&oThis Server is whitelisted!"
FullServer:
  custom: false
  message: "&e{PLAYER}&b, The Server is full &c[{TOTALPLAYERS}/{MAXPLAYERS}]&b!\n&l&dTry to join later :)"
FirstJoin:
  enable: true
  message: "§l§a【§d{PLAYER}§a】§a Chảo Mừng Ngưởi Chơi Mới Đã Tham Gia §eMine§bLight §r "
Join:
  hide: false
  custom: true
  message: "§l§6【§d{PLAYER}§6】§e Đã Tham Gia Máy Chủ §r "
Quit:
  hide: false
  custom: true
  message: "§l§6【§d{PLAYER}§6】§e Đã Thoát Khỏi Máy Chủ §r "
WorldChange:
  enable: false
  message: "&2[{TIME}] &a{PLAYER}&e moved from &c{ORIGIN}&e to &a{TARGET}"
Death:
  hide: false
  custom: true
  message: "§l§6【§d{PLAYER}§6】§e Đã Chết  "
  death-contact-message:
    hide: true
    custom: false
    message: "&cOops! {PLAYER} was killed by {BLOCK}"
  kill-message:
    hide: false
    custom: true
    message: "§l§6【§eMINE§bLIGHT§6】§e§l§d {PLAYER} §eĐã Bị  Giết Bởi§d {KILLER} "
  death-projectile-message:
    hide: false
    custom: true
    message: "§l§6【§eMINE§bLIGHT§6】§d{PLAYER} §eĐã Bị Bắn Chết Bơi§d {KILLER} "
  death-suffocation-message:
    hide: false
    custom: true
    message: "§l§6【§d{PLAYER}§6】§e Đã Chết Vì Nghẹt Thở  "
  death-fall-message:
    hide: false
    custom: true
    message: "§l§6【§d{PLAYER}§6】§e Đã Bị Ngã Gãy Chân  "
  death-fire-message:
    hide: false
    custom: trủ
    message: "§l§6【§d{PLAYER}§6】§e Đã Chết Cháy  "
  death-on-fire-message:
    hide: false
    custom: true
    message: "§l§6【§d{PLAYER}§6】§e Đã Chết Cháy  "
  death-lava-message:
    hide: false
    custom: true
    message: "§l§6【§d{PLAYER}§6】§e Đã Cố Bơi Trong Lava  "
  death-drowning-message:
    hide: false
    custom: true
    message: "§l§6【§d{PLAYER}§6】§e Đã Bị Nghẹt Thở  "
  death-explosion-message:
    hide: false
    custom: true
    message: "§l§6【§d{PLAYER}§6】§e Đã Bị Nổ Banh Xác  "
  death-void-message: 
    hide: false
    custom: true
    message: "§l§6【§d{PLAYER}§6】§e Đã Rơi Xuống Vực Thẳm  "
  death-suicide-message:
    hide: false
    custom: true
    message: "§l§6【§d{PLAYER}§6】§e Đã Tự Tử  "
  death-magic-message:
    hide: false
    custom: true
    message: "§l§6【§d{PLAYER}§6】§e Đã Chết Bởi Một Câu Thần Chú  "
...
