---
kingnight-trangthai: "§l§4Đóng Cửa"
kingnight-ip: "kingnightvn.ddns.net"
kingnight-port: "19132"
aevn-trangthai: "§l§4Đóng Cửa"
aevn-ip: "162.55.242.159"
aevn-port: "19132"
thevertie-trangthai: "§l§2Mở Cửa"
thevertie-ip: "player.thevertie.xyz"
thevertie-port: "19132"
...