---
item-name: §l§eKhiên§b Chrono
item-lore: |-
  §eGiữ hoặc chuột phải để tạo khiên
  §l§eSau 8 Giây Khiên Sẽ Biến Mất
  §l§eKhiên chỉ sử dụng được một lần !
no-permission: §l§c Bạn không có quyền sử dụng lệnh này
...
