# BoostPad Config file.
# Made by BoxOfDevs Team.

# Boost Block ID. ID list: http://minecraft-ids.grahamedgecombe.com/
Block: 165

# Boost Power
BoostPower: 2

# Enable or Disable Flame Particle.
Particle: true