# Internal use only, DO-NOT CHANGE
version: 4

#  ____  _  __    _    _         _       _  
# |  _ \| |/ /   / \  | |__   __| |_   _| |
# | |_) | ' /   / _ \ | '_ \ / _` | | | | |
# |  _ <| . \  / ___ \| |_) | (_| | |_| | |
# |_| \_\_|\_\/_/   \_\_.__/ \__,_|\__,_|_|
#


ore-generator-blocks:
  # Blocks that will spawn ore
  # Format: "ID"
  coal: "232"
  iron: "228"
  gold: "224"
  diamond: "223"
  emerald: "225"
  lapis: "231"
  redstone: "234"

# Name that will be given to each ore spawner
# Use {ore} for the ore type
ore-generators-name: "§l§c•§e OreSpawners§b {ore} §c•"

# Lore that will be given to each ore spawner
# Use {ore} for the ore type
ore-generators-lore: "§l§c•§e Đặt Xuống Đất Để Chúng Spawn Ore {ore} Trên Đầu"

# Whether to generate a cobblestone generator like sound when an ore generates
# Default is true
fizz-sound: true

# Stacking system
stacking: true

# Max limit of stacks on 1 orespawner
max: 5

# Message that will be shown when a user stacks an orespawner
gen-added: "§l§c•§e Đã Chồng Thêm§a 1§e OreSpawners Lên Thành Công"

# Message that will appear when max stacking limit is reached
limit-reached: "§l§c•§e Khối OreSpawner Này Đã Full, Bạn Không Thể Chồng Thêm"

# Drop XP when breaking ores from orespawners
drop-xp: false

# Base time delay you want in seconds in each ore spawn
# If stacking system is on, delay will be counted as base-count divided by stacked amount
base-delay: "1"